### ISSUE TITLE
建议增加safari打包支持

### ISSUE THREAD

**Issue by lichenhao** [zxlie/FeHelper#10]
RT。

**Comment by zxlie** [comment]
做专业前端开发的，应该绝大多数都用chrome的吧？
之前搜狗浏览器占比也不小，所以还特意提供了一个搜狗版本的FeHelper，不过用户反馈并不那么多，所以后期也没做更新；主要还是For chrome了。


原始邮件
发件人:lichenhaonotifications@github.com
收件人:zxlie/FeHelperFeHelper@noreply.github.com
发送时间:2015年10月27日(周二) 14:27
主题:[FeHelper] 建议增加safari打包支持 (#10)


RT。

**Comment by lichenhao** [comment]
最近chrome好像有bug。所以暂时用了safari。只是忽然看到。就想起来而已。后来看了下，很多功能实际上是做不到的，safari做了很多限制。
