### ISSUE TITLE
时间戳转换工具 建议增加复制按钮

### ISSUE THREAD

**Issue by tianyiw2013** [zxlie/FeHelper#106]
`现在的Unix时间戳`变化太快，双击选中后来不及复制就被覆盖了。
我知道可以暂停，但我感觉增加个`复制`按钮会更方便。
可以做两个输入框，把秒和毫秒分开，点击输入框时复制到剪切板。
现在秒和毫秒两个时间戳在同一个输入框，如`1584584547 s   / 1584584546619 ms`，时间戳后面有一个空格s，双击选中时间时容易把空格也复制进去。

**Comment by tianyiw2013** [comment]
`Unix时间戳 转 当地时间` 时间戳转换为时间，`转换单位`选择框可以去掉，s和ms时间戳直接判断长度就好了，没必要手工选择。

**Comment by zxlie** [comment]
收到反馈，随后更新上去

**Comment by zxlie** [comment]
> `现在的Unix时间戳`变化太快，双击选中后来不及复制就被覆盖了。
> 我知道可以暂停，但我感觉增加个`复制`按钮会更方便。
> 可以做两个输入框，把秒和毫秒分开，点击输入框时复制到剪切板。
> 现在秒和毫秒两个时间戳在同一个输入框，如`1584584547 s / 1584584546619 ms`，时间戳后面有一个空格s，双击选中时间时容易把空格也复制进去。

已经更新上去了，到FH设置页手动更新一下吧

**Comment by tianyiw2013** [comment]
毫秒输入框宽度小了点，最后一位没显示出来哦

**Comment by zxlie** [comment]
> 毫秒输入框宽度小了点，最后一位没显示出来哦

随后会更新上去
