### ISSUE TITLE
【代码美化工具】建议自动美化的CSS也用美化工具里的

### ISSUE THREAD

**Issue by SmallOyster** [zxlie/FeHelper#107]
现在新的可以打开JS/CSS文件之后识别并自动美化了，但美化之后的UI好丑啊……
能不能用回之前的css，或者现在的新标签页的工具也行

上图是自动美化的很丑的UI，下图是工具打开新标签页的（手动把代码拷进去美化就很漂亮）
![](https://static.xshgzs.com/image/feScreenShot1.png)

![](https://static.xshgzs.com/image/feScreenShot2.png)

**Comment by zxlie** [comment]
后续会考虑增加自定义皮肤~~~ 「丑」这个东西，是仁者见仁智者见智

**Comment by SmallOyster** [comment]
> 后续会考虑增加自定义皮肤~~~ 「丑」这个东西，是仁者见仁智者见智

emmm好吧，也不是想自定义皮肤就是可能习惯了旧版的，觉得那个比较好

**Comment by zxlie** [comment]
恩，理解，习惯需要培养，哈哈
