### ISSUE TITLE
【信息编码转换】个人建议加上SHA1加密哈

### ISSUE THREAD

**Issue by SmallOyster** [zxlie/FeHelper#111]
只是个人建议，在MD5基础上再加个SHA1。
如果阿烈叔有什么其他建议欢迎吐槽我哈

**Comment by zxlie** [comment]
> 只是个人建议，在MD5基础上再加个SHA1。
> 如果阿烈叔有什么其他建议欢迎吐槽我哈

好的，抽时间加

**Comment by SmallOyster** [comment]
谢谢阿烈叔！！感谢
