### ISSUE TITLE
2020.04.0110 自动美化失效

### ISSUE THREAD

**Issue by zmapleshine** [zxlie/FeHelper#118]
![image](https://user-images.githubusercontent.com/12667610/81380251-2485c300-913d-11ea-955a-ac0a566dfa96.png)

![image](https://user-images.githubusercontent.com/12667610/81380292-3a938380-913d-11ea-963c-4b7362d38f58.png)

![image](https://user-images.githubusercontent.com/12667610/81380329-4f701700-913d-11ea-9a83-7e09d29ab2a2.png)

**Comment by zxlie** [comment]
随表找个JSON地址，打开看下能格式化么？比如： http://t.weather.sojson.com/api/weather/city/101030100 

另外，打开你的FeHelper设置页，手动更新一下「JSON美化工具」试试

**Comment by zmapleshine** [comment]
@zxlie 
![image](https://user-images.githubusercontent.com/12667610/81633211-cc9dd380-943e-11ea-973e-0fc413c78886.png)
当我打开了DevTools，并且当前窗口在DevTools的时候格式化失效，如果浏览器网页窗口在前台就是正常的：

![image](https://user-images.githubusercontent.com/12667610/81633265-edfebf80-943e-11ea-9617-f07f2f5d5982.png)

**Comment by zmapleshine** [comment]
但是我本地测试的端口依然是失效的，这个endpoint是由spring boot 程序提供，之前从来没出现过这种问题。

Request URL: http://127.0.0.1/actuator
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade
Connection: keep-alive
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Tue, 12 May 2020 02:54:36 GMT
Server: nginx/1.15.5
Transfer-Encoding: chunked

**Comment by zmapleshine** [comment]
![image](https://user-images.githubusercontent.com/12667610/81633832-3bc7f780-9440-11ea-87a7-7cb533943cb3.png)

**Comment by zxlie** [comment]
近期JSON工具又有一些小的迭代，你可以再更新一下试试？

**Comment by zmapleshine** [comment]
> 近期JSON工具又有一些小的迭代，你可以再更新一下试试？

刚更新后正常了，感谢。
