### ISSUE TITLE
打开baidu的时候每次都自动搜索FEHELPER，太恶心人了

### ISSUE THREAD

**Issue by useryechen** [zxlie/FeHelper#138]
打开baidu的时候每次都自动搜索FEHELPER，太恶心人了

**Comment by tuobaye0711** [comment]
你把油猴工具里的demo脚本删了或者停用啊
![image](https://user-images.githubusercontent.com/20351109/102890570-a0980580-4497-11eb-93a4-1922d1eaa4d6.png)

**Comment by useryechen** [comment]
> 你把油猴工具里的demo脚本删了或者停用啊
> ![image](https://user-images.githubusercontent.com/20351109/102890570-a0980580-4497-11eb-93a4-1922d1eaa4d6.png)

多谢  已解决
