### ISSUE TITLE
除JSON美化工具外，打开异常

### ISSUE THREAD

**Issue by JacianLiu** [zxlie/FeHelper#141]
Chrome 版本：87.0.4280.88(x86_64)
系统版本：MacOS 11.1
Console异常信息：`Uncaught (in promise) SyntaxError: Unexpected token '<'`
异常界面截图：

![](https://img.jacian.com/note/img20201225162120.png)

![](https://img.jacian.com/note/img20201225162658.png)

问题描述：除JSON美化工具外的所有工具展示异常，功能无法正常使用；已在配置页中更新所有工具（JSON美化工具未更新）

下图为JSON美化工具的展示界面：

![](https://img.jacian.com/note/img20201225162356.png)

下图为配置页截图：

![](https://img.jacian.com/note/img20201225162546.png)

**Comment by jinpy666** [comment]
+1， 确实存在这个问题

**Comment by JacianLiu** [comment]
今天早上尝试更新后，工具可以正常使用了 👍  ：）

**Comment by Jackxwb** [comment]
更新不上。应该说更新完还是页面报错，并且回去插件管理里面更新完刷新一直有个红点

**Comment by SunilWang** [comment]
我打开任何工具都会报 `Unexpected token '<'` 错误。
![image](https://user-images.githubusercontent.com/10388282/183838232-0015c84d-03d6-4472-8824-20c5116020d3.png)
