### ISSUE TITLE
最新版JSON对比工具页面显示为空白页，查看如下报错信息：

### ISSUE THREAD

**Issue by shuchang-wang** [zxlie/FeHelper#150]
![image](https://user-images.githubusercontent.com/42263406/106111816-7b2da400-6187-11eb-9477-6883d38514a4.png)

**Comment by zxlie** [comment]
遇到某个工具不正常的时候，直接在FeHelper的设置页面，重新安装一下对应工具即可，比如你反馈的这个问题，你重新安装一下JSON代码美化工具就好了，一般都是自动更新出的问题

**Comment by shuchang-wang** [comment]
谢谢
