### ISSUE TITLE
JSON 美化 CPU 占用过多，不知道的还以为在挖矿

### ISSUE THREAD

**Issue by Innei** [zxlie/FeHelper#161]
![image](https://user-images.githubusercontent.com/41265413/132805537-4c1f9f52-7d62-4abc-bab9-6731dee2353d.png)

一直报错，CPU 疯狂占用

**Comment by jhhd88** [comment]
+1
特别是js文件特别大的时候，我的风扇就开始疯狂转

**Comment by Innei** [comment]
JSON 也有

**Comment by zctmdc** [comment]
多开两个窗口直接爆炸
![image](https://user-images.githubusercontent.com/24244480/202627112-ef02e567-50b0-4e71-923b-426ddcc4b4d8.png)

**Comment by wolfbolin** [comment]
不清楚为何在完成美化后依然有较高CPU占用，打开两三个Json美化窗口后可以把Chrome卡死
