### ISSUE TITLE
暗黑模式关不掉

### ISSUE THREAD

**Issue by thiskiller** [zxlie/FeHelper#177]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/59038634/168833617-6237ea80-9959-4884-ac0e-9c47998b60c8.png">

不想用暗黑模式，字段名看不清，来回晃动，眼都花了，可是在设置里关不掉，这两天才自动开启的，不是我设置的

**Comment by thiskiller** [comment]
点这里更新
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/59038634/174930639-385c66eb-eaa1-4846-9271-5121016734e6.png">
然后再点高级配置设置自己喜欢的风格
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/59038634/174930800-75fa05f3-67e3-4616-bc1f-5b850240b9dd.png">

**Comment by clamx4** [comment]
I think this issue can be eased by removing the 
```CSS
.theme-default .item .key {
    color: #000
}
```
 in /apps/json-format/without-ui.css.
However, I did not find `.theme-default .item .key` in the without-ui.css on master. I guess the master branch is behind the version of FeHelper extension in Chrome Web Store.
