### ISSUE TITLE
插件导致部分页面无法正常浏览

### ISSUE THREAD

**Issue by CC11001100** [zxlie/FeHelper#190]
比如力扣的这个页面：
```
https://leetcode.cn/problems/1nzheng-shu-zhong-1chu-xian-de-ci-shu-lcof/solutions/934769/1n-zheng-shu-zhong-1-chu-xian-de-ci-shu-umaj8/
```
点进去直接变成了JSON视图：
![image](https://user-images.githubusercontent.com/12819457/207807648-6cc7f5e6-3322-43cc-9f5e-95ce9dc8555b.png)
将插件关闭后页面显示正常：
![image](https://user-images.githubusercontent.com/12819457/207807854-c95ab3c1-c851-41e7-b387-ac5a005b92a6.png)

**Comment by zxlie** [comment]
在即将发布的新版中，这个问题就不会出现了
