### ISSUE TITLE
V2022.12.1616 URL编码解码无法使用

### ISSUE THREAD

**Issue by sevck** [zxlie/FeHelper#202]
Uncaught TypeError: ({(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)} , {} , []) is not a function
    at pako.js:1:46745
(anonymous) @ pako.js:1

![image](https://user-images.githubusercontent.com/11308052/209747661-ca85cdd6-9951-4798-8e1a-4ff2b5d160db.png)

**Comment by zxlie** [comment]
更新到目前的最新版本 V2022.12.2716，可以解决掉哈
