### ISSUE TITLE
最新版本2022.12.1716还是有问题!

### ISSUE THREAD

**Issue by jiayouzl** [zxlie/FeHelper#204]
网页字体在全部加载完成后,会忽然变细+变淡!macos 13.1与macos12.4都有这个问题.

**Comment by jiayouzl** [comment]
关闭你这个插件后就正常了.

**Comment by mirari** [comment]
最新版本是2716

**Comment by zxlie** [comment]
> 最新版本是2716

恩，最新版是这个

@jiayouzl  最新版本 V2022.12.2716 已经审核通过，可以到 chrome://extensions/ 手动更新下；在新版本里，所有样式都会按需注入；之前的样式注入是一个Bug，不是有意为之，望理解哈
