### ISSUE TITLE
右键菜单中找不到美化工具的问题

### ISSUE THREAD

**Issue by Youngsccc** [zxlie/FeHelper#207]
[问题描述] 右键菜单配置了JSON美化工具，但是使用时找不到对应菜单，预期的位置上展示的是设置入口。
- 尝试多次卸载重装，未能解决这个问题。

[插件版本] v2022.12.2716

[操作系统] MacOS 12.6 (21G115)

[浏览器版本] 108.0.5359.124（正式版本）

![截屏2022-12-30 10 24 09](https://user-images.githubusercontent.com/33834662/210028544-0db07138-54a2-4fd5-8458-759c92ba1049.png)

![截屏2022-12-30 10 24 59](https://user-images.githubusercontent.com/33834662/210028558-38261d4c-c3d1-4dd8-84f7-bfd25c826af8.png)

**Comment by StarJiao** [comment]
我也遇到这个问题
原因应该是没加入成功，点击加入右键之后，提示成功，但刷新之后状态会变回来，见图。

![加入右键](https://user-images.githubusercontent.com/18607526/210296644-4e73db86-dca4-402a-a806-f037ae686e45.png)

**Comment by zxlie** [comment]
> [问题描述] 右键菜单配置了JSON美化工具，但是使用时找不到对应菜单，预期的位置上展示的是设置入口。
> 
> * 尝试多次卸载重装，未能解决这个问题。
> 
> [插件版本] v2022.12.2716
> 
> [操作系统] MacOS 12.6 (21G115)
> 
> [浏览器版本] 108.0.5359.124（正式版本）
> 
> ![截屏2022-12-30 10 24 09](https://user-images.githubusercontent.com/33834662/210028544-0db07138-54a2-4fd5-8458-759c92ba1049.png)
> 
> ![截屏2022-12-30 10 24 59](https://user-images.githubusercontent.com/33834662/210028558-38261d4c-c3d1-4dd8-84f7-bfd25c826af8.png)

我环境和你差不多，但是我这里确实没法复现呢；你重启浏览器都不行的么？

**Comment by JIT-ChenXin** [comment]
我也遇到了   加入右键后刷新页面  状态又变成没有加入了
