### ISSUE TITLE
content-script.js:1 Uncaught {name: 'SyntaxError', message: "Unexpected 'u'", at: 1, text: 'undefined'}

### ISSUE THREAD

**Issue by ufec** [zxlie/FeHelper#236]
这是一个紧急bug，插件版本：2023.1.911
问题原因：worker监听消息时，如果是本地域名，动态创建worker会失败，会进一步导致执行环境出现问题，使其不能与其他插件隔离，传入非jsonString参数，进入抛出异常死循环，会卡死浏览器

**Comment by zxlie** [comment]
> 这是一个紧急bug，插件版本：2023.1.911 问题原因：worker监听消息时，如果是本地域名，动态创建worker会失败，会进一步导致执行环境出现问题，使其不能与其他插件隔离，传入非jsonString参数，进入抛出异常死循环，会卡死浏览器

优秀，感谢反馈
