### ISSUE TITLE
[2023.03.2212] 版本引入问题：新加的正则替换处理不符合预期

### ISSUE THREAD

**Issue by arsentiii** [zxlie/FeHelper#257]
数据demo:
[{
 "field_range": "null#13:00-8:00#06:00-10:00#06:00-08:00,06:00-09:00,06:00-10:00"
}]

**Comment by arsentiii** [comment]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/32609689/227894428-5488d12b-abf8-4371-92e1-5c45d1485728.png">

**Comment by arsentiii** [comment]
3.2212版本引入的替换key为str的正则问题。
([{,]\s*)(\w+)(\s*:)

会匹配到value中 ,int 类型

**Comment by zxlie** [comment]
收到，今天发个版本修复掉
