### ISSUE TITLE
JSON美化的BUG

### ISSUE THREAD

**Issue by Anhuike** [zxlie/FeHelper#311]
当一个页面中包含如下代码
![image](https://github.com/zxlie/FeHelper/assets/2849355/ba2a9adf-ce38-4273-a34f-831ef49d04fc)

页面会自动解析，导致页面显示错乱，
![image](https://github.com/zxlie/FeHelper/assets/2849355/8d152456-6210-4c3a-b09e-b4d29217779d)

**Comment by anton-liam** [comment]
主要是 逻辑 解析NUXT3 非SSR模式下的会解析出json. 的bug

**Comment by SeanLeeCai** [comment]
除了暂时关掉FE扩展，有其他解决方法吗？同求

**Comment by cyhhao** [comment]
有什么好办法吗？“总是开启JSON自动格式化功能” 开关设置了也无效
