### ISSUE TITLE
json 数据格式化后卡死

### ISSUE THREAD

**Issue by hutaoseven** [zxlie/FeHelper#32]
格式化 json 后，卡死  version: 2018.7.1312

**Comment by Faiz2** [comment]
我也是这种情况

**Comment by Faiz2** [comment]
@hutaoseven 我的解决了，我从这个网址中重新下载的，https://www.baidufe.com/fehelper/install.html，下载之前先卸载掉

**Comment by hutaoseven** [comment]
@Faiz2 你这是降级了

**Comment by Faiz2** [comment]
没有吧
![image](https://user-images.githubusercontent.com/18616592/42683518-1a9fdda0-86c0-11e8-98bd-1f814fe616fd.png)

**Comment by hutaoseven** [comment]
看提交记录，作者两小时前修复了这个 bug
