### ISSUE TITLE
点击插件ICON无法正常弹出工具菜单

### ISSUE THREAD

**Issue by mx12586** [zxlie/FeHelper#322]
Chrome浏览器插件，最近经常出现工具菜单无法弹出的问题，需要在扩展管理页面，关闭后再开启，就正常了，请问是什么原因？

**浏览器版本信息**
Google Chrome | 118.0.5993.117 (正式版本) (x86_64)
修订版本 | fdb2355de50518294b88ace7bc851820dc38aa82-refs/branch-heads/5993@{#1402}
操作系统 | macOS 版本12.6（版号21G115）

**Comment by mx12586** [comment]
FeHelper版本: 2023.3.2912
已经多次出现了，起初我以为是扩展工具没更新，卸载重装后好了，过了几天还是会出现，暂时还不知道怎么触发的这个问题。

**Comment by sxharl** [comment]
+1

**Comment by xty1992a** [comment]
+1
版本 119.0.6045.159（正式版本） (arm64)
m1 macOS 13.5.1 (22G90)

**Comment by niyangup** [comment]
我也经常出现 不知道啥问题

**Comment by xianghuli** [comment]
+1

**Comment by cccy0** [comment]
+1

**Comment by niyangup** [comment]
哥几个尝试一下
1.把所有页面的devtools关了
2.再次点击FeHelper
试下能打开吗, 我这边亲测可行

**Comment by mx12586** [comment]
> 哥们尝试一下 1.把所有页面的devtools关掉 2.再次点击FeHelper 试下能打开吗，我支持亲测安装

测试确实可行
但是既然叫Web开发助手，却不能在开启DevTools时使用😂
这么久了还没有修复，是不是不维护了
