### ISSUE TITLE
新版的在nuxt3开发的时候会显示异常，自动出现json格式化

### ISSUE THREAD

**Issue by Fyfe0203** [zxlie/FeHelper#325]
<img width="1050" alt="image" src="https://github.com/zxlie/FeHelper/assets/84113519/f88991c5-766e-428a-bc6e-6561db34ee36">
<img width="1415" alt="image" src="https://github.com/zxlie/FeHelper/assets/84113519/1a726011-4790-4be5-887d-670578040911">

新版的在nuxt3开发的时候会显示异常，自动出现json格式化（script里的json也会被自动格式化）

<img width="1024" alt="image" src="https://github.com/zxlie/FeHelper/assets/84113519/e51c1b8e-7f04-42c3-a4eb-6212a8a56ce9">

高级设置里总量开启的关闭了，保存了没效果，下次还是出现

**Comment by mouyong** [comment]
我也遇到了这个问题。

https://github.com/zxlie/FeHelper/issues/355

**Comment by luyaozi** [comment]
所以谁有解决方案吗？
