### ISSUE TITLE
希望大佬能在json格式化页面加一个备注栏

### ISSUE THREAD

**Issue by BillNwc** [zxlie/FeHelper#39]
![image](https://user-images.githubusercontent.com/18160403/47472246-8f63f780-d840-11e8-9cd6-53f3ad6d726e.png)
希望可以在红圈圈那里写上备注，表示我现在是格式化的哪串json，用来干嘛的，如果打开的格式化窗口多的话，这样就可以快速区分了。

**Comment by zxlie** [comment]
举个例子，什么样的备注？

**Comment by BillNwc** [comment]
### 多tab的时候，想有个地方写一下备注，记录我现在看的是哪串json。
### 大概就是这么一个效果图，画的不好见谅~
![image](https://user-images.githubusercontent.com/18160403/47826962-1b809c80-ddb6-11e8-8d35-2bab3522136d.png)
