### ISSUE TITLE
请问能支持火狐浏览器么？

### ISSUE THREAD

**Issue by xb191799981** [zxlie/FeHelper#62]
请问能支持火狐浏览器么？ 谷歌总是要翻墙才能安装，折腾起来有点麻烦。

**Comment by zxlie** [comment]
这里可以直接下载：  https://github.com/zxlie/FeHelper/tree/master/apps/static/screenshot/crx

**Comment by xb191799981** [comment]
这个我试过了， 目前的火狐版本不支持拖放安装的。  我也尝试解压缩crx后打包上传到火狐平台，但依然说不合法。

**Comment by zxlie** [comment]
Firefox版本已出炉：https://www.baidufe.com/item/2038297e9b74c109d542.html

**Comment by zxlie** [comment]
Firefox版直接安装地址：https://addons.mozilla.org/zh-CN/firefox/addon/web%E5%89%8D%E7%AB%AF%E5%8A%A9%E6%89%8B-fehelper/

**Comment by zxlie** [comment]
https://github.com/zxlie/FeHelper/issues/73
