### ISSUE TITLE
可不可以加个base64编解码的功能

### ISSUE THREAD

**Issue by kernellmd** [zxlie/FeHelper#64]

**Comment by zxlie** [comment]
这个工具有啊，位置：字符串编解码 -> Base64 
![屏幕快照 2019-07-08 12 02 35](https://user-images.githubusercontent.com/865735/60782204-507c9480-a178-11e9-970d-92af9cbbdecd.png)

**Comment by kernellmd** [comment]
哦哦，知道了，谢谢

**Comment by ccbikai** [comment]
> 这个工具有啊，位置：字符串编解码 -> Base64
> ![屏幕快照 2019-07-08 12 02 35](https://user-images.githubusercontent.com/865735/60782204-507c9480-a178-11e9-970d-92af9cbbdecd.png)

能不能区分出来 编码/解码，加密/解密, 压缩/解压 。
