### ISSUE TITLE
压缩报错，话说能不能开源压缩代码让自建或者学习一下？

### ISSUE THREAD

**Issue by tcdona** [zxlie/FeHelper#7]
```
XMLHttpRequest cannot load http://baidufe.com/fehelper/fl/compress. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.baidufe.com' is therefore not allowed access. codecompress.html:1
Failed to load resource: net::ERR_CACHE_MISS http://www.baidufe.com/fehelper/codecompress.html
```

**Comment by zxlie** [comment]
抱歉，已修复。


原始邮件
发件人:tcdonanotifications@github.com
收件人:zxlie/FeHelperFeHelper@noreply.github.com
发送时间:2015年1月21日(周三) 12:58
主题:[FeHelper] 压缩报错，话说能不能开源压缩代码让自建或者学习一下？ (#7)


XMLHttpRequest cannot load http://baidufe.com/fehelper/fl/compress. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.baidufe.com' is therefore not allowed access. codecompress.html:1 Failed to load resource: net::ERR_CACHE_MISS http://www.baidufe.com/fehelper/codecompress.html

**Comment by tcdona** [comment]
额，就这么忽略了

**Comment by huguangju** [comment]
@tcdona 压缩的话, 一般用的yahoo的[yuicompressor](https://github.com/yui/yuicompressor)压缩工具, 看文档吧
