### ISSUE TITLE
我的便签笔记功能

### ISSUE THREAD

**Issue by 18801268763** [zxlie/FeHelper#71]
希望能增加便签导入功能，因为一换电脑，之前写的东西没法弄进来，用FeHelper很久了，一直默默支持你们，希望FeHelper能越做越好！！！

**Comment by zxlie** [comment]
OK，我抽时间增加这个功能

**Comment by zxlie** [comment]
在目前的最新版本 V2019.9.315 中已增加此功能：【一键导入】
![屏幕快照 2019-09-03 18 39 33](https://user-images.githubusercontent.com/865735/64166755-517d2a00-ce7a-11e9-8430-7b014f6569a3.png)
