### ISSUE TITLE
火狐的扩展商店没有找到插件

### ISSUE THREAD

**Issue by juzai123** [zxlie/FeHelper#73]
https://addons.mozilla.org/zh-CN/firefox/addon/web%E5%89%8D%E7%AB%AF%E5%8A%A9%E6%89%8B-fehelper/

是已经下架了吗？

**Comment by deverz** [comment]
同问

**Comment by electroniccc** [comment]
同问

**Comment by zxlie** [comment]
直接在本站下载xpi文件，然后拖拽到Firefox安装吧：https://github.com/zxlie/FeHelper/tree/master/apps/static/screenshot/xpi

**Comment by heemoe** [comment]
火狐版没有维护吗?
