### ISSUE TITLE
油猴网页工具怎么引入外部js，如jquery，求示例

### ISSUE THREAD

**Issue by yuanmouren1hao** [zxlie/FeHelper#92]
如题，没有找到相关示例

**Comment by zxlie** [comment]
这个很简单啊，就是正常的JS注入即可，比如：

/* 引入外部脚本，比如JQuery */
(function(){
  let vendor = 'https://code.jquery.com/jquery-3.4.1.min.js';
  document.write(unescape("%3Cscript src='" + vendor + "' type='text/javascript'%3E%3C/script%3E"));
  
  /* Test */
  alert(jQuery)
})();

**Comment by zxlie** [comment]
这个比较简单的，其实就是正常的脚本注入，给你个例子吧：
`
/* 引入外部脚本，比如JQuery */
(function(){
  let vendor = 'https://code.jquery.com/jquery-3.4.1.min.js';
  document.write(unescape("%3Cscript src='" + vendor + "' type='text/javascript'%3E%3C/script%3E"));
  
  /* Test */
  alert(jQuery)
})();
`

**Comment by zxlie** [comment]
这个比较简单的，其实就是正常的脚本注入，给你个例子吧：

```javascript
/* 引入外部脚本，比如JQuery */
(function(){
  let vendor = 'https://code.jquery.com/jquery-3.4.1.min.js';
  document.write(unescape("%3Cscript src='" + vendor + "' type='text/javascript'%3E%3C/script%3E"));
  
  /* Test */
  alert(jQuery)
})();
```

**Comment by lifetin** [comment]
不行,触发安全策略.  有没人有别的办法?
